### ISSUE TITLE
vizsga

### ISSUE THREAD

**Issue by hegyhati** [Teaching-projects/SOE-ProgAlap1-Beadando-MineSweeper-Kelemen#1]
Nem csinaltal issue-t, de ha jol latom, a beadandot megcsinaltad, nezem.

**Comment by hegyhati** [comment]
A generalt pdoc jo lenne, ha fel lenne rakva szinten a repoba.

Amelyik nem random, azt jo volna tesztelni, (doctest-tel foleg).

is_validnal lehet egyszerubb, ha a board-ot adod at, es akkor abban ott van size meg a moves is. de jo igy is.
viszont az is_valid ne printeljen, az cak telrjen vissza, aztan ahol meghivod, ott legyenek a UI uzenetek, szebb ugy.

rekurzionak orulok, szep, ugyes. :-)

a visible_board-ot ketszer hasznalod, mind a ketszer rogton ki is printeled. Lehet szebb volna ugy, hogyha lenne egy `print_visible_board` meg a mostani `print_full_board` fuggveny inkabb, hiszen ugyanannak ket view-jarol van szo. De jo igy is, csak otlet.

Osszessegeben szep munka, tetszik, logikusak a fuggvenyek, jol strukturalt, stb. Lehetne itt-ott aprosagokon kotekedni, de most elegge a finishben vagyunk.

Szeretnek otost adni, de ehhez tessek gyorsan mellerakni a generalt pdoc-ot, es a tesztelheto fuggvenyekhez doctestet irni. 

Egy masik dolog, hogy a fuggvenyeket jol ket csoportra lehet bontani: azok, amik user inputot kezelnek, kiirnak dolgokat, meg azokat, amik "hatterlogikat" csinalnak. Utobbi fuggvenyeked tedd at egy masik modulba, es itt csak importald be. (Egyreszt logikus lenne, masreszt szeretnem latni, hogy tudsz modulokat hasznalni :-) )

@krisztikelemen

**Comment by krisztikelemen** [comment]
En megprobaltam:)

**Comment by hegyhati** [comment]
Gut. Rendben van, bar azert meg irhattal volna tobb tesztet, de rendben latszik a dolog ennyin is. 5.
